name: RIF IDENTITY MANAGER deploy to staging

on:
  pull_request:
    branches:
      - 'develop'
    types: [closed]

jobs:
  develop_build_and_deploy:

    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn

    - name: Build site
      run: yarn build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.DEVELOP_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.DEVELOP_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.DEVELOP_AWS_REGION }}

    - name: Deploy site to S3
      run: |
        aws s3 sync --delete --only-show-errors build/ ${{ secrets.DEVELOP_S3_BUCKET }}

    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.DEVELOP_CLOUDFRONT_DISTRIBUTION }} --paths "/*"
